swap shas for images to fix update issues
securesign/sigstore-ocp pull request #9
Opened 2023-08-14 15:42 UTC by JasonPowr

Quick fix to change the sha's for the image versions to the tags

2023-08-14 17:13 UTC, sallyom commented on examples/values-ez.yaml
> +      version: d2e1b58
that's a weird tag, but it is there, i see it :shrug:

2023-08-14 17:14 UTC, sallyom commented on examples/values-ez.yaml
> +        version: 	v1.2.2
```suggestion
        version: v1.2.2
```

2023-08-14 17:17 UTC, sallyom commented on examples/values-ez.yaml
> +        version: 	v1.4.0
```suggestion
        version: v1.4.0
```

2023-08-14 17:17 UTC, sallyom commented on examples/values-ez.yaml
> +        version: 	v0.6.4
```suggestion
        version: v0.6.4
```

2023-08-14 17:18 UTC, sallyom commented on examples/values-ez.yaml
> +      version: d2e1b58
```suggestion
      version: latest
```

2023-08-14 17:18 UTC, sallyom commented on examples/values-sigstore-openshift.yaml
> +        version: 	v0.6.4
```suggestion
        version: v0.6.4
```

2023-08-14 17:19 UTC, sallyom commented on examples/values-sigstore-openshift.yaml
> +      version: d2e1b58
```suggestion
      version: latest
```

2023-08-14 17:19 UTC, sallyom requested changes
added suggestions for spacing

2023-08-15 08:09 UTC, JasonPowr commented
Apologies for spacing issue, should be all good now :+1:

2023-08-16 02:00 UTC, merged